#define TAPPING_TERM 175
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#define CHARYBDIS_POINTER_ACCELERATION_ENABLE
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 600
#define CHARYBDIS_MINIMUM_SNIPING_DPI 300
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y

#define BILATERAL_COMBINATIONS 200
