#define TAPPING_TERM 175
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#define CHARYBDIS_POINTER_ACCELERATION_ENABLE
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y

#define BILATERAL_COMBINATIONS
